name: Create Tag Cron

on:
  schedule:
    - cron: '0 18 * * 1'

  # TODO: Remove this
  push:
    branches:
      - main

jobs:
  tag-if-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Check if any commits since last release
        id: checker
        run: |
          git fetch --prune --unshallow --tags

          COUNT=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | wc -l)
          echo "::set-output name=commits::${COUNT}"

      - name: Bump version and create tag
        if: steps.checker.outputs.commits > 0
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          npm ci
          npm run release

          git push https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git --follow-tags origin main
