name: Create Tag Cron

on:
  schedule:
    - cron: '0 18 * * 1'

  # TODO: Remove this
  push:
    branches:
      - main

jobs:
  tag-if-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Configure Git
        run: | 
          git config --local "url.https://.insteadOf" "git://"
          git config --local "url.https://jurijzahn8019:${githubToken}@github.com/.insteadOf"  "git@github.com:"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check if any commits since last release
        id: checker
        run: |
          git fetch --prune --unshallow --tags

          COUNT=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | wc -l)
          echo "::set-output name=commits::${COUNT}"

      - name: Bump version and create tag
        if: steps.checker.outputs.commits > 0
        run: |
          npm ci
          npm run release
          git push --follow-tags origin main
