name: "Label Dependabot PR"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: jurijzahn8019/action-dependabot-bump-range@v0.0.5
        id: checker
        env:
          DEBUG: "action-dependabot-bump-range*"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Pull Request Label for Automerge
        uses: actions-ecosystem/action-add-labels@v1

        if: steps.checker.outputs.diff != 'major'

        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          labels: "pull: automerge"

      - name: Add Pull Request Label for Version diff
        uses: actions-ecosystem/action-add-labels@v1

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "dependency: ${{ steps.checker.outputs.diff }}"
