name: "Label Dependabot PR"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  labels:
    runs-on: ubuntu-latest

    # run only for dependabot prs
    if: startsWith(github.event.pull_request.user.login, 'dependabot')

    steps:
      - uses: jurijzahn8019/action-dependabot-labels@v0.1.5
        env:
          DEBUG: "action-dependabot-labels:*"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
