name: Release from Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: "Create Github Release"
    runs-on: ubuntu-latest

    steps:
      - name: Check Tag
        run: |
          if [[ $GITHUB_REF =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then 
            echo "::debug::This is a Release"; 
            echo "::set-env name=IS_RELEASE::true"
          else 
            echo "::debug::This is a Pre-Release"; 
            echo "::set-env name=IS_RELEASE::false"
          fi;

      - if: env.IS_RELEASE == 'false'
        name: Prerelease
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          allow_override: true
          prerelease: true

      - if: env.IS_RELEASE == 'true'
        name: Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          allow_override: true
